services:
  - type: web
    name: alex-booking-backend
    runtime: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: "22"
